version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install"

  build:
    commands:
      - echo "Build phase running..."
      - echo "Hello from CI/CD demo"

artifacts:
  files:
    - '**/*'

